name: Stale Issues & PRs

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    if: contains(fromJSON('["folke", "LazyVim"]'), github.repository_owner)
    uses: folke/github/.github/workflows/stale.yml@main
    secrets: inherit
